### ISSUE TITLE
Cant creat a "Zuwendungsbescheinigung"

### ISSUE THREAD

**Issue by ulimoebius** [systopia/de.systopia.donrec#124]
Auf Deutsch:
Nach Update auf Version 2.0, CiviCRM 5.19.1., Drupal 7
Wenn ich eine "Zuwendungsbescheinigung" erstellen möchte, kommt folgende Fehlermeldung:
"Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
DB Error: no such table"

civicrm.XXX.log schreibt:

Mar 18 17:23:26  [error] $Fatal Error Details = Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => handle
        )

    [code] => -18
    [message] => DB Error: no such table
    [mode] => 16
    [debug_info] => DELETE FROM `donrec_snapshot`
       WHERE `expires_timestamp` < NOW(); [nativecode=1146 ** Table 'civicrmDB.donrec_snapshot' doesn't exist]
    [type] => DB_Error
    [user_info] => DELETE FROM `donrec_snapshot`
       WHERE `expires_timestamp` < NOW(); [nativecode=1146 ** Table 'civicrmDB.donrec_snapshot' doesn't exist]
    [to_string] => [db_error: message="DB Error: no such table" code=-18 mode=callback callback=CRM_Core_Error::handle prefix="" info="DELETE FROM `donrec_snapshot`
       WHERE `expires_timestamp` < NOW(); [nativecode=1146 ** Table 'civicrmDB.donrec_snapshot' doesn't exist]"]
)

Mar 18 17:23:26  [debug] $backTrace = #0 /var/www/drupal/sites/all/modules/civicrm/CRM/Core/Error.php(236): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /var/www/drupal/sites/all/modules/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(922): CRM_Core_Error::handle(Object(DB_Error))
#2 /var/www/drupal/sites/all/modules/civicrm/packages/DB.php(987): PEAR_Error->__construct("DB Error: no such table", -18, 16, (Array:2), "DELETE FROM `donrec_snapshot`\n       WHERE `expires_timestamp` < NOW(); [nat...")
#3 /var/www/drupal/sites/all/modules/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(575): DB_Error->__construct(-18, 16, (Array:2), "DELETE FROM `donrec_snapshot`\n       WHERE `expires_timestamp` < NOW(); [nat...")
#4 /var/www/drupal/sites/all/modules/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(223): PEAR->_raiseError(Object(DB_mysqli), NULL, -18, 16, (Array:2), "DELETE FROM `donrec_snapshot`\n       WHERE `expires_timestamp` < NOW(); [nat...", "DB_Error", TRUE)
#5 /var/www/drupal/sites/all/modules/civicrm/packages/DB/common.php(1920): PEAR->__call("raiseError", (Array:7))
#6 /var/www/drupal/sites/all/modules/civicrm/packages/DB/mysqli.php(933): DB_common->raiseError(-18, NULL, NULL, "DELETE FROM `donrec_snapshot`\n       WHERE `expires_timestamp` < NOW(); [nat...", "1146 ** Table 'civicrmDB.donrec_snapshot' doesn't exist")
#7 /var/www/drupal/sites/all/modules/civicrm/packages/DB/mysqli.php(403): DB_mysqli->mysqliRaiseError()
#8 /var/www/drupal/sites/all/modules/civicrm/packages/DB/common.php(1229): DB_mysqli->simpleQuery("DELETE FROM `donrec_snapshot`\n       WHERE `expires_timestamp` < NOW();")
#9 /var/www/drupal/sites/all/modules/civicrm/packages/DB/DataObject.php(2416): DB_common->query("DELETE FROM `donrec_snapshot`\n       WHERE `expires_timestamp` < NOW();")
#10 /var/www/drupal/sites/all/modules/civicrm/packages/DB/DataObject.php(1607): DB_DataObject->_query("DELETE FROM `donrec_snapshot`\n       WHERE `expires_timestamp` < NOW();")
#11 /var/www/drupal/sites/all/modules/civicrm/CRM/Core/DAO.php(435): DB_DataObject->query("DELETE FROM `donrec_snapshot`\n       WHERE `expires_timestamp` < NOW();")
#12 /var/www/drupal/sites/all/modules/civicrm/CRM/Core/DAO.php(1493): CRM_Core_DAO->query("DELETE FROM `donrec_snapshot`\n       WHERE `expires_timestamp` < NOW();", TRUE)
#13 /var/www/drupal/sites/default/files/civicrm/extensions/de.systopia.donrec/CRM/Donrec/Logic/Snapshot.php(409): CRM_Core_DAO::singleValueQuery("DELETE FROM `donrec_snapshot`\n       WHERE `expires_timestamp` < NOW();")
#14 /var/www/drupal/sites/default/files/civicrm/extensions/de.systopia.donrec/CRM/Donrec/Form/Task/Create.php(57): CRM_Donrec_Logic_Snapshot::cleanup()
#15 /var/www/drupal/sites/all/modules/civicrm/CRM/Core/Form.php(613): CRM_Donrec_Form_Task_Create->setDefaultValues()
#16 /var/www/drupal/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Display.php(92): CRM_Core_Form->buildForm()
#17 /var/www/drupal/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Display->perform(Object(CRM_Donrec_Form_Task_Create), "display")
#18 /var/www/drupal/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Donrec_Form_Task_Create), "display")
#19 /var/www/drupal/sites/all/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("display")
#20 /var/www/drupal/sites/all/modules/civicrm/CRM/Utils/Wrapper.php(114): CRM_Core_Controller->run()
#21 /var/www/drupal/sites/all/modules/civicrm/CRM/Core/Invoke.php(263): CRM_Utils_Wrapper->run("CRM_Donrec_Form_Task_Create", "Issue Donation Receipts", (Array:0))
#22 /var/www/drupal/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:13))
#23 /var/www/drupal/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#24 /var/www/drupal/sites/all/modules/civicrm/drupal/civicrm.module(444): CRM_Core_Invoke::invoke((Array:3))
#25 /var/www/drupal/includes/menu.inc(527): civicrm_invoke("donrec", "create")
#26 /var/www/drupal/index.php(21): menu_execute_active_handler()
#27 {main}

Mär 18 17:30:09  [warning] Deprecated function CRM_Core_BAO_Query::getFieldName, use These parameters should be standardised before we get here.
Array
(
    [civi.tag] => deprecated
)

**Comment by ulimoebius** [comment]
Ein Blick in die Datenbank hat bestätigt: donrec_snapshot existiert nicht (mehr). Mein IT-Kollege meint sich an die Updateanleitung gehalten zu haben (alte Version deaktivieren, neue Version einspielen und Datenbank update). Es hat auch alle Einstellungen und Profile in die neue Version übernommen. Nur donrec_snapshot ist verschwunden. Ich schlug vor, einfach den Befehl aus der master/sql/donrec.sql auszuführen. Der Kollege ist sich aber unsicher ob dann alle Abhängigkeiten richtig gesetzt sind.

**Comment by bjendres** [comment]
Das ist komisch, denn ein ``DROP TABLE IF EXISTS `donrec_snapshot`;`` wird im Code ausschließlich bei der Deinstallation aufgerufen.

@ulimoebius Ist es möglich dass ihr nicht nur deaktiviert, sondern auch *deinstalliert* habt? Ansonsten müsste es einen anderen Grund geben...

**Comment by ulimoebius** [comment]
Nur deaktiviert und Ordner umbenannt. Mein Kollege schaut jetzt mal in Datensicherungen vor dem Update und dann melden wir uns.

**Comment by jensschuppe** [comment]
@ulimoebius Ist das noch aktuell? / Is this still relevant?
