### ISSUE TITLE
 Call to a member function getProfile() on null in CRM_Donrec_Logic_Settings::validateContribution()

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.donrec#147]
There seems to be issues with the locking algorithm in certain circumstances:
```
Error: Call to a member function getProfile() on null in CRM_Donrec_Logic_Settings::validateContribution() (line 180 of [drupal_root]/web/sites/default/files/civicrm/ext/de.systopia.donrec/CRM/Donrec/Logic/Settings.php)
#0 [drupal_root]/web/sites/default/files/civicrm/ext/de.systopia.donrec/donrec.php(354): CRM_Donrec_Logic_Settings::validateContribution(1, Array, Array)
#1 [drupal_root]/vendor/civicrm/civicrm-core/CRM/Utils/Hook.php(287): donrec_civicrm_validateForm('CRM_Contribute_...', Array, Array, Object(CRM_Contribute_Form_Contribution), Array)
#2 [drupal_root]/vendor/civicrm/civicrm-core/CRM/Utils/Hook/DrupalBase.php(73): CRM_Utils_Hook->runHooks(Array, 'civicrm_validat...', 5, 'CRM_Contribute_...', Array, Array, Object(CRM_Contribute_Form_Contribution), Array, NULL)
#3 [drupal_root]/vendor/civicrm/civicrm-core/Civi/Core/CiviEventDispatcher.php(253): CRM_Utils_Hook_DrupalBase->invokeViaUF(5, 'CRM_Contribute_...', Array, Array, Object(CRM_Contribute_Form_Contribution), Array, NULL, 'civicrm_validat...')
#4 [drupal_root]/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Civi\Core\CiviEventDispatcher::delegateToUF(Object(Civi\Core\Event\GenericHookEvent), 'hook_civicrm_va...', Object(Civi\Core\CiviEventDispatcher))
#5 [drupal_root]/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'hook_civicrm_va...', Object(Civi\Core\Event\GenericHookEvent))
#6 [drupal_root]/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'hook_civicrm_va...', Object(Civi\Core\Event\GenericHookEvent))
#7 [drupal_root]/vendor/civicrm/civicrm-core/Civi/Core/CiviEventDispatcher.php(198): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Civi\Core\Event\GenericHookEvent), Object(Civi\Core\Event\GenericHookEvent))
#8 [drupal_root]/vendor/civicrm/civicrm-core/CRM/Utils/Hook.php(167): Civi\Core\CiviEventDispatcher->dispatch('hook_civicrm_va...', Object(Civi\Core\Event\GenericHookEvent))
#9 [drupal_root]/vendor/civicrm/civicrm-core/CRM/Utils/Hook.php(512): CRM_Utils_Hook->invoke(Array, 'CRM_Contribute_...', Array, Array, Object(CRM_Contribute_Form_Contribution), Array, NULL, 'civicrm_validat...')
#10 [drupal_root]/vendor/civicrm/civicrm-core/CRM/Core/Form.php(637): CRM_Utils_Hook::validateForm('CRM_Contribute_...', Array, Array, Object(CRM_Contribute_Form_Contribution), Array)
#11 [drupal_root]/vendor/civicrm/civicrm-core/CRM/Core/QuickForm/Action/Upload.php(136): CRM_Core_Form->validate()
#12 [drupal_root]/vendor/civicrm/civicrm-core/CRM/Core/QuickForm/Action/Upload.php(119): CRM_Core_QuickForm_Action_Upload->realPerform(Object(CRM_Contribute_Form_Contribution), 'upload')
#13 [drupal_root]/vendor/civicrm/civicrm-packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Upload->perform(Object(CRM_Contribute_Form_Contribution), 'upload')
#14 [drupal_root]/vendor/civicrm/civicrm-packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Contribute_Form_Contribution), 'upload')
#15 [drupal_root]/vendor/civicrm/civicrm-core/CRM/Core/Controller.php(353): HTML_QuickForm_Page->handle('upload')
#16 [drupal_root]/vendor/civicrm/civicrm-core/CRM/Contribute/Page/Tab.php(401): CRM_Core_Controller->run()
#17 [drupal_root]/vendor/civicrm/civicrm-core/CRM/Contribute/Page/Tab.php(457): CRM_Contribute_Page_Tab->edit()
#18 [drupal_root]/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php(319): CRM_Contribute_Page_Tab->run(Array, NULL)
#19 [drupal_root]/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem(Array)
#20 [drupal_root]/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke(Array)
#21 [drupal_root]/web/modules/contrib/civicrm/src/Civicrm.php(88): CRM_Core_Invoke::invoke(Array)
#22 [drupal_root]/web/modules/contrib/civicrm/src/Controller/CivicrmController.php(80): Drupal\civicrm\Civicrm->invoke(Array)
[...]
```

DonRec version: ``2.1-beta1``
CiviCRM version: ``5.46.0``

**Comment by bjendres** [comment]
Looks like ``CRM_Donrec_Logic_Settings::validateContribution`` needs to be more robust.

**Comment by jensschuppe** [comment]
@bjendres Could you decide whether #159 fixes this issue or we should move this to the `2.2` milestone until the scenario is clear enough for a review?

**Comment by bjendres** [comment]
> @bjendres Could you decide whether #159 fixes this issue or we should move this to the `2.2` milestone until the scenario is clear enough for a review?

It *looks* like it should prevent this issue from happening, yes. However, since I don't know in which scenarios this issue occurred in the first place, I don't know if this is now _fixed_, or simply not throwing a warning any more.

@jensschuppe we can either leave it a this, or invest time into finding out where this report came from, reproduce the error, and then verify that your fix does the right thing. 

I think we have better things to invest our time into, and we can still revisit this if a similar problem resurfaces - agreed?

**Comment by jensschuppe** [comment]
D'Accord, moving to the `2.2` milestone.
